language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - android-24
    - build-tools-24.0.3
    
licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+
